<?php /* Smarty version 2.6.27, created on 2013-07-13 11:44:23
         compiled from plugins/menu-list.tpl */

$this->_cache_serials['/Applications/MAMP/dev.local/ska/internal_c/components/gold2/navigation_sub_menu/%%AA/AAE/AAE9B68C%%menu-list.tpl.inc'] = '21e0fb2e3fe983eefac2c5579127b4d0';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'strip', 'plugins/menu-list.tpl', 7, false),)), $this); ?>
<?php
function _smarty_tplfunc_21e0fb2e3fe983eefac2c5579127b4d0_0(&$_smarty)
{
$_smarty->includeCSSFile('http://dev.local/ska/external_c/gold2/%25%2527/27D/27D2E248%25%25menu-list.style.css?51e183e7f0a2f');

}



?>
