<?php /* Smarty version 2.6.27, created on 2013-07-13 10:39:50
         compiled from themes/gold2/plugins/menu-tabs.tpl */

$this->_cache_serials['/Applications/MAMP/dev.local/ska/internal_c/components/gold2/navigation_menu_main/%%23/23A/23A14E48%%menu-tabs.tpl.inc'] = '64e01961e240bd73889a83794674484a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'strip', 'themes/gold2/plugins/menu-tabs.tpl', 4, false),)), $this); ?>
<?php
function _smarty_tplfunc_64e01961e240bd73889a83794674484a_0(&$_smarty)
{
$_smarty->includeCSSFile('http://dev.local/ska/external_c/gold2/%25%25DD/DDC/DDC58E77%25%25menu-tabs.style.css?51e174c6b91b6');

}



?>
