<?php /* Smarty version 2.6.27, created on 2013-07-13 10:39:50
         compiled from themes/gold2/plugins/menu-tabs.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'strip', 'themes/gold2/plugins/menu-tabs.tpl', 4, false),)), $this); ?>
<?php $this->_cache_serials['/Applications/MAMP/dev.local/ska/internal_c/components/gold2/navigation_menu_main/%%23/23A/23A14E48%%menu-tabs.tpl.inc'] = '64e01961e240bd73889a83794674484a'; ?>
<?php if ($this->caching && !$this->_cache_including): echo '{nocache:64e01961e240bd73889a83794674484a#0}'; endif;$this->includeCSSFile('http://dev.local/ska/external_c/gold2/%25%25DD/DDC/DDC58E77%25%25menu-tabs.style.css?51e174c6b91b6');
if ($this->caching && !$this->_cache_including): echo '{/nocache:64e01961e240bd73889a83794674484a#0}'; endif; ?>
<?php echo '<ul class="menu-tabs'; ?><?php if ($this->_tpl_vars['class']): ?><?php echo ' '; ?><?php echo $this->_tpl_vars['class']; ?><?php echo ''; ?><?php endif; ?><?php echo '">'; ?><?php $_from = $this->_tpl_vars['items']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }$this->_foreach['item'] = array('total' => count($_from), 'iteration' => 0);
if ($this->_foreach['item']['total'] > 0):
    foreach ($_from as $this->_tpl_vars['item']):
        $this->_foreach['item']['iteration']++;
?><?php echo '<li class="tab '; ?><?php if ($this->_tpl_vars['item']['active']): ?><?php echo 'active'; ?><?php endif; ?><?php echo ' '; ?><?php if (($this->_foreach['item']['iteration'] <= 1)): ?><?php echo 'first'; ?><?php endif; ?><?php echo ' '; ?><?php if (($this->_foreach['item']['iteration'] == $this->_foreach['item']['total'])): ?><?php echo 'last'; ?><?php endif; ?><?php echo '"><a class="'; ?><?php if ($this->_tpl_vars['item']['active']): ?><?php echo 'active'; ?><?php endif; ?><?php echo ' '; ?><?php if (isset ( $this->_tpl_vars['item']['class'] )): ?><?php echo ''; ?><?php echo $this->_tpl_vars['item']['class']; ?><?php echo ''; ?><?php endif; ?><?php echo '" href="'; ?><?php echo $this->_tpl_vars['item']['href']; ?><?php echo '" '; ?><?php if ($this->_tpl_vars['empty']): ?><?php echo 'title="'; ?><?php echo ((is_array($_tmp=$this->_tpl_vars['item']['label'])) ? $this->_run_mod_handler('strip', true, $_tmp) : smarty_modifier_strip($_tmp)); ?><?php echo '"'; ?><?php endif; ?><?php echo '><span>'; ?><?php if ($this->_tpl_vars['empty']): ?><?php echo '&nbsp;'; ?><?php else: ?><?php echo ''; ?><?php echo ((is_array($_tmp=$this->_tpl_vars['item']['label'])) ? $this->_run_mod_handler('strip', true, $_tmp) : smarty_modifier_strip($_tmp)); ?><?php echo ''; ?><?php endif; ?><?php echo '</span></a></li>'; ?><?php endforeach; endif; unset($_from); ?><?php echo '</ul>'; ?>