<?php /* Smarty version 2.6.27, created on 2013-07-13 11:47:01
         compiled from components/important_tips/default.tpl */

$this->_cache_serials['/Applications/MAMP/dev.local/ska/internal_c/components/gold2/important_tips/%%00/00F/00F72758%%default.tpl.inc'] = 'a187752e6d1e1fefd883308c57404f0d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('block', 'block', 'components/important_tips/default.tpl', 5, false),)), $this); ?>
<?php
function _smarty_tplfunc_a187752e6d1e1fefd883308c57404f0d_0(&$_smarty)
{
$_smarty->includeCSSFile('http://dev.local/ska/external_c/gold2/important_tips/%25%25E2/E25/E2580E09%25%25important_tips.style.css?51e184856a56f');

?>
<div id="<?php echo SK_Layout::current_component()->auto_id; ?>" class="important_tips">
<?php

}


function _smarty_tplfunc_a187752e6d1e1fefd883308c57404f0d_1(&$_smarty)
{

?>
</div>
<?php

}



?>
