<?php /* Smarty version 2.6.27, created on 2013-07-13 11:47:01
         compiled from components/contact_importer_buttons/default.tpl */

$this->_cache_serials['/Applications/MAMP/dev.local/ska/internal_c/components/gold2/contact_importer_buttons/%%5C/5C5/5C583A91%%default.tpl.inc'] = 'd2b5ce575439e2ddbd61273541f363d7';

?><?php
function _smarty_tplfunc_d2b5ce575439e2ddbd61273541f363d7_0(&$_smarty)
{
$_smarty->includeCSSFile('http://dev.local/ska/external_c/gold2/float_right%2Bcontact_importer_buttons/%25%258C/8C5/8C5A5A38%25%25contact_importer_buttons.style.css?51e1848563639');

?>
<div id="<?php echo SK_Layout::current_component()->auto_id; ?>" class="float_right contact_importer_buttons">
<?php

}


function _smarty_tplfunc_d2b5ce575439e2ddbd61273541f363d7_1(&$_smarty)
{
echo 'id="'.SK_Layout::current_component()->getTagAutoId('google').'"';
}


function _smarty_tplfunc_d2b5ce575439e2ddbd61273541f363d7_2(&$_smarty)
{

?>
</div>
<?php

}



?>
