<?php /* Smarty version 2.6.27, created on 2013-07-13 10:40:55
         compiled from themes/gold2/canvas/default/footer.tpl */

$this->_cache_serials['/Applications/MAMP/dev.local/ska/internal_c/components/gold2/join/%%29/29B/29BA70D3%%footer.tpl.inc'] = '52aff07989cd80df0ebadf8ca86e7121';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'ads', 'themes/gold2/canvas/default/footer.tpl', 7, false),)), $this); ?>
<?php
function _smarty_tplfunc_52aff07989cd80df0ebadf8ca86e7121_0(&$_smarty)
{

$component = SK_Component('PageFooter');

echo $_smarty->renderComponent($component);

}



?>
