<?php /* Smarty version 2.6.27, created on 2013-07-13 11:47:01
         compiled from themes/gold2/plugins/menu-vertical.tpl */

$this->_cache_serials['/Applications/MAMP/dev.local/ska/internal_c/components/gold2/member_console/%%3E/3E3/3E33066C%%menu-vertical.tpl.inc'] = '1ee74cae67a046794c6068af547d4073';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'strip', 'themes/gold2/plugins/menu-vertical.tpl', 7, false),)), $this); ?>
<?php
function _smarty_tplfunc_1ee74cae67a046794c6068af547d4073_0(&$_smarty)
{
$_smarty->includeCSSFile('http://dev.local/ska/external_c/gold2/%25%2541/41D/41DA6436%25%25menu-vertical.style.css?51e184850495c');

}



?>
