<?php /* Smarty version 2.6.27, created on 2013-07-13 11:47:00
         compiled from components/im_listener/default.tpl */

$this->_cache_serials['/Applications/MAMP/dev.local/ska/internal_c/components/gold2/im_listener/%%AE/AEC/AECC2FF9%%default.tpl.inc'] = 'b8ef7939e308ebb57d4d3841263eb634';

?><?php
function _smarty_tplfunc_b8ef7939e308ebb57d4d3841263eb634_0(&$_smarty)
{
$_smarty->includeCSSFile('http://dev.local/ska/external_c/gold2/im_listener/%25%2587/873/87372032%25%25im_listener.style.css?51e18484eb76d');

?>
<div id="<?php echo SK_Layout::current_component()->auto_id; ?>" class="im_listener">
<?php

}


function _smarty_tplfunc_b8ef7939e308ebb57d4d3841263eb634_1(&$_smarty)
{
echo 'id="'.SK_Layout::current_component()->getTagAutoId('im_invitaion_tpl').'"';
}


function _smarty_tplfunc_b8ef7939e308ebb57d4d3841263eb634_2(&$_smarty)
{
echo 'id="'.SK_Layout::current_component()->getTagAutoId('im_invitations').'"';
}


function _smarty_tplfunc_b8ef7939e308ebb57d4d3841263eb634_3(&$_smarty)
{

?>
</div>
<?php

}



?>
