<?php /* Smarty version 2.6.27, created on 2013-07-13 11:47:01
         compiled from components/event_speed_dating_notifier/default.tpl */

$this->_cache_serials['/Applications/MAMP/dev.local/ska/internal_c/components/gold2/event_speed_dating_notifier/%%89/895/8959A287%%default.tpl.inc'] = '27614b592bc84c71683be1d1ce992c90';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('block', 'block', 'components/event_speed_dating_notifier/default.tpl', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_27614b592bc84c71683be1d1ce992c90_0(&$_smarty)
{
$_smarty->includeCSSFile('http://dev.local/ska/external_c/gold2/event_speed_dating_notifier/%25%258A/8A2/8A2973BD%25%25style.style.css?51e184850abd1');

?>
<div id="<?php echo SK_Layout::current_component()->auto_id; ?>" class="event_speed_dating_notifier">
<?php

}


function _smarty_tplfunc_27614b592bc84c71683be1d1ce992c90_1(&$_smarty)
{
echo 'id="'.SK_Layout::current_component()->getTagAutoId('event_speed_dating_notifier_content').'"';
}


function _smarty_tplfunc_27614b592bc84c71683be1d1ce992c90_2(&$_smarty)
{
echo 'id="'.SK_Layout::current_component()->getTagAutoId('esd_notifier_submit').'"';
}


function _smarty_tplfunc_27614b592bc84c71683be1d1ce992c90_3(&$_smarty)
{

?>
</div>
<?php

}



?>
