<?php /* Smarty version 2.6.27, created on 2013-07-13 10:41:38
         compiled from themes/gold2/canvas/centered/footer.tpl */

$this->_cache_serials['/Applications/MAMP/dev.local/ska/internal_c/components/gold2/sign_in/%%6F/6F1/6F18FAB6%%footer.tpl.inc'] = '6f4f1f305fbf72189cd171ab27c2b0a4';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'ads', 'themes/gold2/canvas/centered/footer.tpl', 8, false),)), $this); ?>
<?php
function _smarty_tplfunc_6f4f1f305fbf72189cd171ab27c2b0a4_0(&$_smarty)
{

$component = SK_Component('PageFooter');

echo $_smarty->renderComponent($component);

}



?>
