<?php /* Smarty version 2.6.27, created on 2013-07-13 10:39:51
         compiled from components/sign_up_link/default.tpl */

$this->_cache_serials['/Applications/MAMP/dev.local/ska/internal_c/components/gold2/sign_up_link/%%97/97C/97C430A1%%default.tpl.inc'] = '41e235397e22219a6e0ed561fa64cc4c';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('block', 'block', 'components/sign_up_link/default.tpl', 4, false),array('block', 'block_cap', 'components/sign_up_link/default.tpl', 5, false),array('function', 'document_url', 'components/sign_up_link/default.tpl', 7, false),)), $this); ?>
<?php
function _smarty_tplfunc_41e235397e22219a6e0ed561fa64cc4c_0(&$_smarty)
{
$_smarty->includeCSSFile('http://dev.local/ska/external_c/gold2/sign_up_link/%25%25C3/C36/C3614276%25%25sign_up_link.style.css?51e174c7eb21f');

?>
<div id="<?php echo SK_Layout::current_component()->auto_id; ?>" class="sign_up_link">
<?php

}


function _smarty_tplfunc_41e235397e22219a6e0ed561fa64cc4c_1(&$_smarty)
{

?>
</div>
<?php

}



?>
