<?php /* Smarty version 2.6.27, created on 2013-07-13 10:39:52
         compiled from components/bread_crumb/default.tpl */

$this->_cache_serials['/Applications/MAMP/dev.local/ska/internal_c/components/gold2/bread_crumb/%%41/41F/41F7CDF4%%default.tpl.inc'] = 'a05cea468eb865c43e6088183bf2930d';

?><?php
function _smarty_tplfunc_a05cea468eb865c43e6088183bf2930d_0(&$_smarty)
{

?>
<div id="<?php echo SK_Layout::current_component()->auto_id; ?>" class="bread_crumb">
<?php

}


function _smarty_tplfunc_a05cea468eb865c43e6088183bf2930d_1(&$_smarty)
{

?>
</div>
<?php

}



?>
