<?php /* Smarty version 2.6.27, created on 2013-07-13 11:47:01
         compiled from components/text_formatter/default.tpl */

$this->_cache_serials['/Applications/MAMP/dev.local/ska/internal_c/components/gold2/text_formatter/%%AD/ADB/ADB67330%%default.tpl.inc'] = '977ced988f21ccad413509d284afa69b';

?><?php
function _smarty_tplfunc_977ced988f21ccad413509d284afa69b_0(&$_smarty)
{
$_smarty->includeCSSFile('http://dev.local/ska/external_c/gold2/text_formatter/%25%254A/4A7/4A7444E3%25%25text_formatter.style.css?51e184857ce18');

?>
<div id="<?php echo SK_Layout::current_component()->auto_id; ?>" class="text_formatter">
<?php

}


function _smarty_tplfunc_977ced988f21ccad413509d284afa69b_1(&$_smarty)
{
echo 'id="'.SK_Layout::current_component()->getTagAutoId("smile-box-c").'"';
}


function _smarty_tplfunc_977ced988f21ccad413509d284afa69b_2(&$_smarty)
{
echo 'id="'.SK_Layout::current_component()->getTagAutoId("smile-box").'"';
}


function _smarty_tplfunc_977ced988f21ccad413509d284afa69b_3(&$_smarty)
{

?>
</div>
<?php

}



?>
