<?php /* Smarty version 2.6.27, created on 2013-07-13 11:53:29
         compiled from themes/gold2/canvas/default/footer.tpl */

$this->_cache_serials['/Applications/MAMP/dev.local/ska/internal_c/components/gold2/group_list/%%29/29B/29BA70D3%%footer.tpl.inc'] = '38a434e732f17f52d9b091a981170291';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'ads', 'themes/gold2/canvas/default/footer.tpl', 7, false),)), $this); ?>
<?php
function _smarty_tplfunc_38a434e732f17f52d9b091a981170291_0(&$_smarty)
{

$component = SK_Component('PageFooter');

echo $_smarty->renderComponent($component);

}



?>
