<?php /* Smarty version 2.6.27, created on 2013-07-13 11:47:00
         compiled from components/navigation_inventory_line/default.tpl */

$this->_cache_serials['/Applications/MAMP/dev.local/ska/internal_c/components/gold2/navigation_inventory_line/%%9B/9BF/9BF6EE35%%default.tpl.inc'] = '0894733159b4e1bec6beb4b958c47c0f';

?><?php
function _smarty_tplfunc_0894733159b4e1bec6beb4b958c47c0f_0(&$_smarty)
{
$_smarty->includeCSSFile('http://dev.local/ska/external_c/gold2/inventory_line/%25%250F/0F7/0F7D975C%25%25inventory.style.css?51e18484c5956');

?>
<div id="<?php echo SK_Layout::current_component()->auto_id; ?>" class="inventory_line">
<?php

}


function _smarty_tplfunc_0894733159b4e1bec6beb4b958c47c0f_1(&$_smarty)
{

?>
</div>
<?php

}



?>
