<?php /* Smarty version 2.6.27, created on 2013-07-13 11:47:01
         compiled from components/newsfeed/no_permission.tpl */

$this->_cache_serials['/Applications/MAMP/dev.local/ska/internal_c/components/gold2/newsfeed/%%50/501/5018BD3A%%no_permission.tpl.inc'] = '94e277b02e20c385119d4218c6c7956d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('block', 'block_cap', 'components/newsfeed/no_permission.tpl', 4, false),array('block', 'block', 'components/newsfeed/no_permission.tpl', 5, false),)), $this); ?>
<?php
function _smarty_tplfunc_94e277b02e20c385119d4218c6c7956d_0(&$_smarty)
{
$_smarty->includeCSSFile('http://dev.local/ska/external_c/gold2/newsfeed/%25%250E/0E5/0E56E51C%25%25newsfeed.style.css?51e1848541e9f');

?>
<div id="<?php echo SK_Layout::current_component()->auto_id; ?>" class="newsfeed">
<?php

}


function _smarty_tplfunc_94e277b02e20c385119d4218c6c7956d_1(&$_smarty)
{

?>
</div>
<?php

}



?>
