<?php /* Smarty version 2.6.27, created on 2013-07-13 10:39:50
         compiled from components/navigation_menu_main/default.tpl */

$this->_cache_serials['/Applications/MAMP/dev.local/ska/internal_c/components/gold2/navigation_menu_main/%%6F/6F9/6F9E93B7%%default.tpl.inc'] = '179db275f69ef4cd01553ae4b3398f34';

?><?php
function _smarty_tplfunc_179db275f69ef4cd01553ae4b3398f34_0(&$_smarty)
{
$_smarty->includeCSSFile('http://dev.local/ska/external_c/gold2/main_menu/%25%255D/5D9/5D9D69D1%25%25menu_main.style.css?51e174c6aeb6d');

?>
<div id="<?php echo SK_Layout::current_component()->auto_id; ?>" class="main_menu">
<?php

}


function _smarty_tplfunc_179db275f69ef4cd01553ae4b3398f34_1(&$_smarty)
{

?>
</div>
<?php

}



?>
