<?php /* Smarty version 2.6.27, created on 2013-07-13 11:47:01
         compiled from components/index_news/default.tpl */

$this->_cache_serials['/Applications/MAMP/dev.local/ska/internal_c/components/gold2/index_news/%%12/12F/12FB438C%%default.tpl.inc'] = 'c4753130faa8c65de4d2390bc5ca3353';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('block', 'block_cap', 'components/index_news/default.tpl', 6, false),array('block', 'block', 'components/index_news/default.tpl', 11, false),array('function', 'profile_thumb', 'components/index_news/default.tpl', 18, false),array('modifier', 'censor', 'components/index_news/default.tpl', 21, false),array('modifier', 'spec_date', 'components/index_news/default.tpl', 22, false),array('modifier', 'smile', 'components/index_news/default.tpl', 24, false),array('modifier', 'out_format', 'components/index_news/default.tpl', 24, false),)), $this); ?>
<?php
function _smarty_tplfunc_c4753130faa8c65de4d2390bc5ca3353_0(&$_smarty)
{

?>
<div id="<?php echo SK_Layout::current_component()->auto_id; ?>" class="index_news">
<?php

}


function _smarty_tplfunc_c4753130faa8c65de4d2390bc5ca3353_1(&$_smarty)
{

?>
</div>
<?php

}



?>
