<?php /* Smarty version 2.6.27, created on 2013-07-13 10:39:52
         compiled from themes/gold2/canvas/default/footer.tpl */

$this->_cache_serials['/Applications/MAMP/dev.local/ska/internal_c/components/gold2/custom_pages/%%29/29B/29BA70D3%%footer.tpl.inc'] = 'f46be4acb5e260d372c9559e43eb7afb';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'ads', 'themes/gold2/canvas/default/footer.tpl', 7, false),)), $this); ?>
<?php
function _smarty_tplfunc_f46be4acb5e260d372c9559e43eb7afb_0(&$_smarty)
{

$component = SK_Component('PageFooter');

echo $_smarty->renderComponent($component);

}



?>
