<?php /* Smarty version 2.6.27, created on 2013-07-13 10:39:51
         compiled from components/navigation_sub_menu/default.tpl */

$this->_cache_serials['/Applications/MAMP/dev.local/ska/internal_c/components/gold2/navigation_sub_menu/%%DA/DA9/DA97BF5D%%default.tpl.inc'] = 'd950b4cc382e667aab416b4d784f0941';

?><?php
function _smarty_tplfunc_d950b4cc382e667aab416b4d784f0941_0(&$_smarty)
{
$_smarty->includeCSSFile('http://dev.local/ska/external_c/gold2/submenu/%25%253D/3DA/3DADC1F8%25%25navigation_sub_menu.style.css?51e174c7df8a4');

?>
<div id="<?php echo SK_Layout::current_component()->auto_id; ?>" class="submenu">
<?php

}


function _smarty_tplfunc_d950b4cc382e667aab416b4d784f0941_1(&$_smarty)
{

?>
</div>
<?php

}



?>
