<?php /* Smarty version 2.6.27, created on 2013-07-13 10:39:52
         compiled from components/hot_list/default.tpl */

$this->_cache_serials['/Applications/MAMP/dev.local/ska/internal_c/components/gold2/hot_list/%%1A/1A5/1A5A261C%%default.tpl.inc'] = '2db324a122c0e2fc974bc408eee11abc';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('block', 'block', 'components/hot_list/default.tpl', 3, false),array('function', 'cycle', 'components/hot_list/default.tpl', 6, false),array('function', 'profile_thumb', 'components/hot_list/default.tpl', 7, false),array('function', 'document_url', 'components/hot_list/default.tpl', 13, false),)), $this); ?>
<?php
function _smarty_tplfunc_2db324a122c0e2fc974bc408eee11abc_0(&$_smarty)
{
$_smarty->includeCSSFile('http://dev.local/ska/external_c/gold2/hot_list/%25%25E4/E46/E46CC0BF%25%25hot_list.style.css?51e174c8124eb');

?>
<div id="<?php echo SK_Layout::current_component()->auto_id; ?>" class="hot_list">
<?php

}


function _smarty_tplfunc_2db324a122c0e2fc974bc408eee11abc_1(&$_smarty)
{
echo 'id="'.SK_Layout::current_component()->getTagAutoId('become_hot').'"';
}


function _smarty_tplfunc_2db324a122c0e2fc974bc408eee11abc_2(&$_smarty)
{

?>
</div>
<?php

}



?>
