<?php /* Smarty version 2.6.27, created on 2013-07-13 11:47:01
         compiled from components/shoutbox/default.tpl */

$this->_cache_serials['/Applications/MAMP/dev.local/ska/internal_c/components/gold2/shoutbox/%%D0/D01/D0164C4A%%default.tpl.inc'] = '074834d2d8161d518a7134a157844961';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('block', 'block', 'components/shoutbox/default.tpl', 4, false),array('function', 'palette_picker', 'components/shoutbox/default.tpl', 57, false),array('function', 'smileset', 'components/shoutbox/default.tpl', 58, false),)), $this); ?>
<?php
function _smarty_tplfunc_074834d2d8161d518a7134a157844961_0(&$_smarty)
{
$_smarty->includeCSSFile('http://dev.local/ska/external_c/gold2/shoutbox/%25%257B/7BF/7BFD9248%25%25shoutbox.style.css?51e184858402a');

?>
<div id="<?php echo SK_Layout::current_component()->auto_id; ?>" class="shoutbox">
<?php

}


function _smarty_tplfunc_074834d2d8161d518a7134a157844961_1(&$_smarty)
{
echo 'id="'.SK_Layout::current_component()->getTagAutoId('message_tpl').'"';
}


function _smarty_tplfunc_074834d2d8161d518a7134a157844961_2(&$_smarty)
{
echo 'id="'.SK_Layout::current_component()->getTagAutoId('window').'"';
}


function _smarty_tplfunc_074834d2d8161d518a7134a157844961_3(&$_smarty)
{
echo 'id="'.SK_Layout::current_component()->getTagAutoId('msg_list').'"';
}


function _smarty_tplfunc_074834d2d8161d518a7134a157844961_4(&$_smarty)
{
echo 'id="'.SK_Layout::current_component()->getTagAutoId('bottom').'"';
}


function _smarty_tplfunc_074834d2d8161d518a7134a157844961_5(&$_smarty)
{
echo 'id="'.SK_Layout::current_component()->getTagAutoId('shoutbox_input_form').'"';
}


function _smarty_tplfunc_074834d2d8161d518a7134a157844961_6(&$_smarty)
{
echo 'id="'.SK_Layout::current_component()->getTagAutoId('username').'"';
}


function _smarty_tplfunc_074834d2d8161d518a7134a157844961_7(&$_smarty)
{
echo 'id="'.SK_Layout::current_component()->getTagAutoId('input').'"';
}


function _smarty_tplfunc_074834d2d8161d518a7134a157844961_8(&$_smarty)
{
echo 'id="'.SK_Layout::current_component()->getTagAutoId('send_btn').'"';
}


function _smarty_tplfunc_074834d2d8161d518a7134a157844961_9(&$_smarty)
{

?>
</div>
<?php

}



?>
