<?php /* Smarty version 2.6.27, created on 2013-07-13 11:47:00
         compiled from plugins/menu-line.tpl */

$this->_cache_serials['/Applications/MAMP/dev.local/ska/internal_c/components/gold2/navigation_inventory_line/%%48/482/482119FB%%menu-line.tpl.inc'] = 'dacf463c3504bfce47edcc56294c170a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'strip', 'plugins/menu-line.tpl', 4, false),)), $this); ?>
<?php
function _smarty_tplfunc_dacf463c3504bfce47edcc56294c170a_0(&$_smarty)
{
$_smarty->includeCSSFile('http://dev.local/ska/external_c/gold2/%25%2501/01C/01C551C8%25%25menu-line.style.css?51e18484c9494');

}



?>
