<?php /* Smarty version 2.6.27, created on 2013-07-13 11:47:01
         compiled from themes/gold2/canvas/default/footer.tpl */

$this->_cache_serials['/Applications/MAMP/dev.local/ska/internal_c/components/gold2/member_home/%%29/29B/29BA70D3%%footer.tpl.inc'] = '4feeccda0a50d57c6805b07cd28fa7f4';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'ads', 'themes/gold2/canvas/default/footer.tpl', 7, false),)), $this); ?>
<?php
function _smarty_tplfunc_4feeccda0a50d57c6805b07cd28fa7f4_0(&$_smarty)
{

$component = SK_Component('PageFooter');

echo $_smarty->renderComponent($component);

}



?>
