<?php /* Smarty version 2.6.27, created on 2013-07-13 11:47:01
         compiled from components/member_home_links/default.tpl */

$this->_cache_serials['/Applications/MAMP/dev.local/ska/internal_c/components/gold2/member_home_links/%%DA/DAE/DAE6E449%%default.tpl.inc'] = 'e397e31b374c8eea5eb9346a3c5d67e1';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('block', 'block', 'components/member_home_links/default.tpl', 7, false),array('function', 'memberhome_href', 'components/member_home_links/default.tpl', 9, false),)), $this); ?>
<?php
function _smarty_tplfunc_e397e31b374c8eea5eb9346a3c5d67e1_0(&$_smarty)
{
$_smarty->includeCSSFile('http://dev.local/ska/external_c/gold2/memberhome_hrefs_cont/%25%25AB/ABA/ABA21878%25%25member_home_links.style.css?51e184852161f');

?>
<div id="<?php echo SK_Layout::current_component()->auto_id; ?>" class="memberhome_hrefs_cont">
<?php

}


function _smarty_tplfunc_e397e31b374c8eea5eb9346a3c5d67e1_1(&$_smarty)
{

?>
</div>
<?php

}



?>
