<?php /* Smarty version 2.6.27, created on 2013-07-13 10:39:50
         compiled from plugins/menu-line-bottom.tpl */

$this->_cache_serials['/Applications/MAMP/dev.local/ska/internal_c/components/gold2/page_footer/%%EA/EAB/EAB112B7%%menu-line-bottom.tpl.inc'] = '2887cf49655b02c35b77411c9389d17d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'strip', 'plugins/menu-line-bottom.tpl', 7, false),)), $this); ?>
<?php
function _smarty_tplfunc_2887cf49655b02c35b77411c9389d17d_0(&$_smarty)
{
$_smarty->includeCSSFile('http://dev.local/ska/external_c/gold2/%25%25CA/CAD/CADB2AD9%25%25menu-line-bottom.style.css?51e174c6dd579');

}



?>
